# Generated by Django 4.2.7 on 2025-04-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mabutu', '0002_post_comment_emojireaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
